In [0]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn import datasets

In [36]:
data = pd.read_csv('https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/results.csv')
result=data[["resultId","raceId","driverId", "constructorId","time"]]
datap= pd.read_csv("https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/drivers.csv",encoding = "ISO-8859-1")
drivers=datap[["driverId","driverRef","code"]]
weath=pd.read_csv("https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/Weather_SafetyCar.csv",encoding='utf-8')
weather=weath[["year","name","weather"]]
cir=pd.read_csv('https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/races.csv')
circuit=cir[["raceId","year","name"]]
resultdrivers = pd.merge(result,drivers,left_on='driverId', right_on="driverId")
resultdriverweather=pd.merge(resultanddrivers,cirweath, left_on='raceId', right_on="raceId")
resultdriverweather.head(10)
final=resultdriverweather[["driverRef","name","weather","time"]]
final.rename({"name":"circuit"},axis=1)
final.head(10)

    driverRef                   name weather     time
0    hamilton  Australian Grand Prix     Dry  34:50.6
1    heidfeld  Australian Grand Prix     Dry    5.478
2     rosberg  Australian Grand Prix     Dry    8.163
3      alonso  Australian Grand Prix     Dry   17.181
4  kovalainen  Australian Grand Prix     Dry   18.014
5    nakajima  Australian Grand Prix     Dry      NaN
6    bourdais  Australian Grand Prix     Dry      NaN
7   raikkonen  Australian Grand Prix     Dry      NaN
8      kubica  Australian Grand Prix     Dry      NaN
9       glock  Australian Grand Prix     Dry      NaN

In [29]:
cirweath = pd.merge(circuit,weather,left_on=['year',"name"], right_on=["year","name"])
cirweath.head(10)

   raceId  year                   name weather
0       1  2009  Australian Grand Prix     Dry
1       2  2009   Malaysian Grand Prix  Varied
2       3  2009     Chinese Grand Prix     Wet
3       4  2009     Bahrain Grand Prix     Dry
4       5  2009     Spanish Grand Prix     Dry
5       6  2009      Monaco Grand Prix     Dry
6       7  2009     Turkish Grand Prix     Dry
7       8  2009     British Grand Prix     Dry
8       9  2009      German Grand Prix     Dry
9      10  2009   Hungarian Grand Prix     Dry

In [35]:
cir=pd.read_csv('https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/races.csv')
circuit=cir[["raceId","year","name"]]
circuit.rename(column

   raceId  year                   name
0       1  2009  Australian Grand Prix
1       2  2009   Malaysian Grand Prix
2       3  2009     Chinese Grand Prix
3       4  2009     Bahrain Grand Prix
4       5  2009     Spanish Grand Prix
5       6  2009      Monaco Grand Prix
6       7  2009     Turkish Grand Prix
7       8  2009     British Grand Prix
8       9  2009      German Grand Prix
9      10  2009   Hungarian Grand Prix

In [27]:
weath=pd.read_csv("https://raw.githubusercontent.com/XaviJunior/omega/Data/Data/Weather_SafetyCar.csv",encoding='utf-8')
weather=weath[["year","name","weather"]]
weather.head(10)

   year                   name weather
0  2008  Australian Grand Prix     Dry
1  2008   Malaysian Grand Prix     Dry
2  2008     Bahrain Grand Prix     Dry
3  2008     Spanish Grand Prix     Dry
4  2008     Turkish Grand Prix     Dry
5  2008      Monaco Grand Prix     Wet
6  2008    Canadian Grand Prix     Dry
7  2008      French Grand Prix     Dry
8  2008     British Grand Prix     Wet
9  2008      German Grand Prix     Dry